version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: casa-vc-solutions_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/vdanesi/vc-solutions-dashboard:1.19.0
    init: true
    restart: on-failure
    environment:
      PORT: 8080
      COLLECTOR_URL: http://collector:8090
    depends_on:
      - collector
    volumes:
      - ${APP_DATA_DIR}/data:/data

  collector:
    image: ghcr.io/vdanesi/vc-solutions-collector:1.19.0
    init: true
    restart: on-failure
    environment:
      PORT: 8090
      HOST_ROOT: /host
      NETWORK_TARGETS: "INTERNET / WAN|ICMP|1.1.1.1|UPLINK;CASAOS|HTTPS|https://dash.dvso.net/|REMOTE DOCKER HOST"
      DISCOVERY_SUBNETS: "192.168.3.0/24"
      DISCOVERY_TTL: "60000"
      SNMP_COMMUNITY: "public"
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
